### PR TITLE
[thermalctld] Use interval set in thermal policy if available

### PR DESCRIPTION
**Pull request by andywongarista**
#### Description
Update thermalctld to retrieve interval from thermal manager (which in turn loads an interval from thermal_policy.json) instead of using a constant.

#### Motivation and Context

https://github.com/Azure/sonic-platform-common/pull/178

This will allow platform vendors to specify an alternate interval for running thermal policies, e.g. 15 seconds instead of the current 60.

#### How Has This Been Tested?

Verified that thermalctld runs without exiting.
Also ran test_thermalctld.py

### CODE REVIEW

**Comment by jleveque** [comment]
Please fix new conflicts

**Comment by jleveque** [comment]
@Junchao-Mellanox: Please review.

**Comment by jleveque** [comment]
@Junchao-Mellanox: Please review.

**Comment by jleveque** [comment]
It looks like something went wrong with your latest push. Can you please rebase against the latest master?

**Review by sujinmkang — APPROVED** [review]

**Comment by sujinmkang** [comment]
lgtm

**Pull request merged**
