### PR TITLE
[CI] Sum up Azp unit test code coverage

### PR DESCRIPTION
**Pull request by liushilongbuaa**
#### Description

Azp code coverage result is one of the six components by random.
This PR summarized all six components test coverage.

### CODE REVIEW

**Comment by lguohan** [comment]
image

can you check?

**Comment by lguohan** [comment]
please have a good title description.

**Comment by liushilongbuaa** [comment]
> image
> 
> can you check why it says only one coverage report is used?

At the [overview page](https://dev.azure.com/mssonic/build/_build/results?buildId=26324&view=results), it choose one of the six code coverage results. 70%
when we clicked in the [details](https://dev.azure.com/mssonic/build/_build/results?buildId=26324&view=codecoverage-tab), it shows the coverage is 52%. It is the right result.

**Pull request closed without merging**
