### PR TITLE
[thermalctld] Update line card thermal sensor status to DB

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
Update line card thermal sensor status to DB, includes PSU thermal sensors and SFP thermal sensors on line card. Depends on https://github.com/Azure/sonic-buildimage/pull/8422.

#### Description

In thermal update function, update PSU, SFP and direct thermal of line card

#### Motivation and Context

To support modular chassis

#### How Has This Been Tested?

1. Full platform regression, 100% passed
2. Unit test passed

### CODE REVIEW

**Review by keboliu — DISMISSED** [review]

**Comment by liat-grozovik** [comment]
@keboliu please review

**Comment by liat-grozovik** [comment]
@lguohan  please assign someone to review

**Comment by dprital** [comment]
@vdahiya12  - Can you please review ?

**Comment by liat-grozovik** [comment]
@vdahiya12 and @keboliu could you please both approve so we can merge?

**Review by keboliu — APPROVED** [review]

**Pull request merged**
