### PR TITLE
[multi-asic] Xcvrd process to exit if there are no Front End ASIC's

### PR DESCRIPTION
**Pull request by judyjoseph**
Closes issue: https://github.com/Azure/sonic-buildimage/issues/6097

### CODE REVIEW

**Comment by anamehra** [comment]
Is this change really required? pmon_daemon_control.json should be good enough to block spawning of xcvrd if required. We may have future use for this process on a distributed system.

**Comment by judyjoseph** [comment]
> Is this change really required? pmon_daemon_control.json should be good enough to block spawning of xcvrd if required. We may have future use for this process on a distributed system.

The intend I had was to prevent XCRVd from crashing in case a user didn't know about the skip pmon daemon control pmon_daemon_control.json. There are places in the xcvrd code where we assume the front-end asic's are present by default -- which may not be the case in for eg: fabric cards in Chassis. 
Also Could you specify the future use case which you were referring here ?

**Comment by anamehra** [comment]
> > Is this change really required? pmon_daemon_control.json should be good enough to block spawning of xcvrd if required. We may have future use for this process on a distributed system.
> 
> The intend I had was to prevent XCRVd from crashing in case a user didn't know about the skip pmon daemon control pmon_daemon_control.json. There are places in the xcvrd code where we assume the front-end asic's are present by default -- which may not be the case in for eg: fabric cards in Chassis.
> Also Could you specify the future use case which you were referring here ?
I was thinking about if xcrvd on Controller card should handle LC transreceivers as pseudo devices to handle OIR during LC OIR. But I think that could be part of chassis fault handling design. I think for now, it should be fine to disable this.

**Review by anamehra — APPROVED** [review]

**Comment by judyjoseph** [comment]
If the xcvrd exit in between, it will cause the pmon docker to exit as it is a critical process. So I will not put this fix, would stick to the skip_flags in the pmon_daemon_control.json file itself to control whether we need to have xcvrd in pmon or not. Closing this PR.

**Pull request closed without merging**
