### PR TITLE
[CI] Sum up Azp unit test code coverage

### PR DESCRIPTION
**Pull request by liushilongbuaa**
#### Description

1. Azp code coverage result is one of the six components by random. This PR summarized all six components test coverage.
2. Use one container to improve time efficiency.
3. Parameterize download artifacts.
#### Motivation and Context

Fix code coverage display error in azp.
Build in multiple containers didn't improve time efficiency.
#### How Has This Been Tested?

Check code coverage result in Checks/azure pipeline

### CODE REVIEW

**Comment by qiluo-msft** [comment]
LGTM. Wait PR build result.

**Comment by liushilongbuaa** [comment]
> LGTM. Wait PR build result.

result is here: https://dev.azure.com/mssonic/build/_build/results?buildId=26985&view=results
Because I have changed 7 parallel jobs into 1 serial job, PR check seems not finished. But actually it is finished.

**Review by qiluo-msft — APPROVED** [review]

**Comment by liushilongbuaa** [comment]
PR checker will not pass at all. Because 7 old jobs is replaced by 1 new job.
why I changed 7 jobs to 1 job? Because 7 parallel jobs didn't save time. They waste a lot of time downloading the same container and same artifacts.

**Comment by qiluo-msft** [comment]
The PR checkers are actually passed. Check the `Checks` page. I will override and merge.

**Pull request merged**
