### PR TITLE
[psud] Add PSU Hardware Revision to Redis STATE_DB

### PR DESCRIPTION
**Pull request by robocoder99**
#### Description
Added "hardware revision" field to list of platform fields to sync to STATE_DB for the PSU. Also updated relevant unit tests. 

#### Motivation and Context
Now that hardware revision exists as a platform 2.0 field for all devices, it is appropriate to synchronize this field to STATE_DB for PSUs as is done with all other fields. This will allow this field to be exposed to CLI tools through psushow in the future which reads state from STATE_DB. 

#### How Has This Been Tested?

This has been tested on all mellanox platforms aside from MSN2010. Tested by deploying change and verifying that "revision" was present in STATE_DB for all platforms that support it.

### CODE REVIEW

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@robocoder99 is this OR pending on other PRs to be merged first? if so, can you please add?

**Comment by robocoder99** [comment]
This PR can safely be merged without the Mellanox implementation (as it has to be tolerant of other vendor non-implemented status) it just won't do anything.

**Comment by jleveque** [comment]
@robocoder99: Can you please also add a regression test in https://github.com/Azure/sonic-mgmt/blob/master/tests/platform_tests/api/test_psu.py to ensure vendors are aware they need to implement the new method for their platforms?

**Comment by robocoder99** [comment]
Yes, that is in progress (done but in Mellanox internal review)

**Pull request merged**
